# Generated by Django 4.2.6 on 2023-10-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='cooking.jpg', upload_to='images'),
        ),
    ]
